<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo-steel-check.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\logo-steel-check.png" />
    <Resource Include="Assets\logo-steel-check.ico" />
    <Reference Include="CSiAPIv1">
      <HintPath>Lib\ETABS22\CSiAPIv1.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
